### ISSUE TITLE
output after prediction is not correct

### ISSUE THREAD

**Issue by ma-siddiqui** [ayushdabra/dubai-satellite-imagery-segmentation#3]
Hi,

I have run the predition on one of the image but predicted masks seeems to be wrong. please guide what could be the issue.

**Comment by ma-siddiqui** [comment]
![sat_img_preds](https://user-images.githubusercontent.com/42836589/222908472-b362e6b6-dd7a-46ee-9821-9cca6a924bd5.png)

**Comment by ma-siddiqui** [comment]
the output is attached

**Comment by ayushdabra** [comment]
Hi Ajmal, did you use the pre-trained weights for prediction?

**Comment by ma-siddiqui** [comment]
yes, it was my bad. i did not normlize the input data. after normalizing it, my issue solved. thanks.

**Comment by jjaegii** [comment]
@ma-siddiqui 
Can I ask you about the code for normalizing the input image?

**Comment by ShaoshuSu** [comment]
> @ma-siddiqui Can I ask you about the code for normalizing the input image?

Hi @jjaegii ,

You could try `img = img/255.0`
